#!/bin/sh

rm -f /usr/local/etc/ttyd.crt \
	/usr/local/etc/ttyd.key \
	/var/log/ttyd.log \
	/usr/local/etc/pfsense_ttyd.credential \
	/usr/local/etc/pfsense_ttyd.crt \
	/usr/local/etc/pfsense_ttyd.key \
	/var/log/pfsense_ttyd.log \
	/usr/local/etc/pfsense_webssh.credential \
	/usr/local/etc/pfsense_webssh.crt \
	/usr/local/etc/pfsense_webssh.key \
	/var/log/pfsense_webssh.log

rm -rf /usr/local/share/ttyd-for-pfsense
rm -rf /usr/local/pfSense-pkg-ttyd

php <<'PHP'
<?php
require_once('/etc/inc/config.inc');

function remove_entries_by_match($path, $matches) {
	$entries = config_get_path($path, []);
	if (!is_array($entries)) {
		return;
	}

	$entries = array_values(array_filter($entries, function($entry) use ($matches) {
		if (!is_array($entry)) {
			return true;
		}
		foreach ($matches as $key => $value) {
			if (($entry[$key] ?? null) !== $value) {
				return true;
			}
		}
		return false;
	}));

	config_set_path($path, $entries);
	write_config('Remove ttyd for pfSense package metadata');
}

remove_entries_by_match('installedpackages/menu', [
	'name' => 'Web SSH Shell',
	'section' => 'Diagnostics',
]);
remove_entries_by_match('installedpackages/menu', [
	'name' => 'ttyd',
	'section' => 'Diagnostics',
]);
remove_entries_by_match('installedpackages/service', [
	'name' => 'pfsense_webssh',
]);
remove_entries_by_match('installedpackages/service', [
	'name' => 'pfsense_ttyd',
]);
remove_entries_by_match('installedpackages/service', [
	'name' => 'ttyd',
]);
remove_entries_by_match('installedpackages/package', [
	'name' => 'pfsensettyd',
]);
remove_entries_by_match('installedpackages/package', [
	'name' => 'pfsensewebssh',
]);
remove_entries_by_match('installedpackages/package', [
	'name' => 'pfsense_webssh',
]);
remove_entries_by_match('installedpackages/package', [
	'name' => 'pfsense_ttyd',
]);
remove_entries_by_match('installedpackages/package', [
	'name' => 'ttyd',
]);
PHP

exit 0
